# Generated by Django 4.2.2 on 2023-06-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aluno_disciplina_matricula_universidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='universidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.universidade'),
            preserve_default=False,
        ),
    ]
