# Generated by Django 4.2.2 on 2023-06-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mymodel_aluno_universidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
