# Generated by Django 4.2.2 on 2023-06-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoSigiloso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_nascimento', models.DateField()),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.aluno')),
            ],
        ),
    ]
