# Generated by Django 4.2.2 on 2023-06-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alunosigiloso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosigiloso',
            name='data_nascimento',
            field=models.CharField(max_length=10),
        ),
    ]
