# Generated by Django 4.2.2 on 2023-06-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_alunosigiloso_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosigiloso',
            name='data_nascimento',
            field=models.CharField(max_length=15),
        ),
    ]
