# Generated by Django 4.2.2 on 2023-06-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_alunosigiloso_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunosigiloso',
            name='sexo',
        ),
    ]
