# Generated by Django 4.2.2 on 2023-06-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_alunosigiloso_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunosigiloso',
            name='sexo',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunosigiloso',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
