# Generated by Django 4.2.2 on 2023-06-20 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alunosigiloso_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosigiloso',
            name='aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aluno'),
        ),
        migrations.AlterField(
            model_name='alunosigiloso',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alunosigiloso',
            name='sexo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
