# Generated by Django 4.2.2 on 2023-06-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_alunosigiloso_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosigiloso',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
