# Generated by Django 4.2.2 on 2023-06-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_aluno_curso_alter_aluno_universidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='teste',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alunosigiloso',
            name='teste',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
