# Generated by Django 4.2.2 on 2023-06-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_aluno_teste_alunosigiloso_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='teste',
        ),
        migrations.RemoveField(
            model_name='alunosigiloso',
            name='teste',
        ),
    ]
